### ISSUE TITLE
Super 99.9 PRO_MAX_ULTRA 的视频播放不支持Linux

### ISSUE THREAD

**Issue by xiaozhangup** [hanbao233xD/EndMinecraftPlus2#2]
卡死在第一帧
![image](https://user-images.githubusercontent.com/68374769/162196883-4379e61e-ef38-46ae-922c-3b9b8563d384.png)

报错：
xiaozhangup@xiaozhangup:~/下载$ java -jar EMP2_PRO_MAX_ULTRA.jar 
java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2423)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1402)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1269)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:362)
	at rickroll.Rickroll.playVideo(Rickroll.java:100)
	at rickroll.Rickroll.main(Rickroll.java:271)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniavutil in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1767)
	... 13 more

**Comment by hanbao233xD** [comment]
这个是从别地方偷来的（
